import { prisma } from "../src/database/prisma";

async function seed() {
  await prisma.fish.createMany({
    data: [
      {
        name: "Molly",
        scientificName: "Poecilia sphenops",
        image:
          "https://riverparkaquatics.co.uk/wp-content/uploads/2020/05/Assorted-Molly-Poecilia-sphenops.jpg",
        minTankSize: 15,
        temperament: "Calmo",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Eum nulla expedita quia quidem facilis consequatur sint adipisci consequatur placeat recusandae sapiente ipsa debitis illo nulla ex itaque cumque quos accusantium.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 29.9,
      },
      {
        name: "Discus",
        scientificName: "Symphysodon aequifasciatus",
        image: "https://example.com/fish/discus.jpg",
        minTankSize: 10,
        temperament: "Agressivo com machos",
        diet: "Onívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Perspiciatis laboriosam esse dolorum suscipit provident accusamus voluptatum illum distinctio voluptatibus culpa quis minima nihil animi nulla nesciunt blanditiis nostrum quos hic ullam eligendi repudiandae mollitia repellendus.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 59.9,
      },
      {
        name: "Swordtail",
        scientificName: "Xiphophorus hellerii",
        image: "https://example.com/fish/swordtail.jpg",
        minTankSize: 10,
        temperament: "Agressivo com machos",
        diet: "Onívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Veniam non mollitia facere a officiis recusandae facere quia voluptatibus eaque eum ullam facilis dolore quasi facilis.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 24.9,
      },
      {
        name: "Swordtail",
        scientificName: "Xiphophorus hellerii",
        image: "https://example.com/fish/swordtail.jpg",
        minTankSize: 20,
        temperament: "Territorial",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Perferendis beatae aut facilis dignissimos sapiente incidunt excepturi qui hic beatae esse veritatis eveniet hic aliquid sequi natus placeat cumque ipsam tempora magnam quia excepturi perferendis minima.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 24.9,
      },
      {
        name: "Zebra Danio",
        scientificName: "Danio rerio",
        image: "https://example.com/fish/zebra-danio.jpg",
        minTankSize: 5,
        temperament: "Territorial",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Esse quia enim praesentium nobis facilis expedita voluptatum dolores expedita blanditiis ipsa fuga placeat cumque.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 12.9,
      },
      {
        name: "Discus",
        scientificName: "Symphysodon aequifasciatus",
        image: "https://example.com/fish/discus.jpg",
        minTankSize: 20,
        temperament: "Pacífico",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Fugiat ratione nihil dolores possimus necessitatibus voluptates distinctio beatae possimus dolore distinctio praesentium doloremque occaecati fugiat consequatur cumque facere et.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 59.9,
      },
      {
        name: "Goldfish",
        scientificName: "Carassius auratus",
        image: "https://example.com/fish/goldfish.jpg",
        minTankSize: 15,
        temperament: "Pacífico",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Aliquam nulla numquam at quos nesciunt consequuntur id a culpa similique laudantium qui unde incidunt laborum.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 19.9,
      },
      {
        name: "Platy",
        scientificName: "Xiphophorus maculatus",
        image: "https://example.com/fish/platy.jpg",
        minTankSize: 20,
        temperament: "Agressivo com machos",
        diet: "Onívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Sit est reprehenderit similique qui incidunt aspernatur quisquam vel sed nihil a deleniti.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 14.9,
      },
      {
        name: "Molly",
        scientificName: "Poecilia sphenops",
        image: "https://example.com/fish/molly.jpg",
        minTankSize: 20,
        temperament: "Pacífico",
        diet: "Onívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Saepe distinctio ipsum totam corporis dolor magnam libero praesentium debitis aspernatur quod at occaecati a deleniti quo enim possimus.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 29.9,
      },
      {
        name: "Swordtail",
        scientificName: "Xiphophorus hellerii",
        image: "https://example.com/fish/swordtail.jpg",
        minTankSize: 15,
        temperament: "Territorial",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Esse perspiciatis blanditiis est reprehenderit nam porro deserunt dolore cum temporibus porro numquam.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 24.9,
      },
      {
        name: "Harlequin Rasbora",
        scientificName: "Trigonostigma heteromorpha",
        image: "https://example.com/fish/harlequin-rasbora.jpg",
        minTankSize: 20,
        temperament: "Calmo",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Eaque eveniet explicabo dignissimos maxime quos quia consequatur inventore fugiat autem voluptas commodi id nostrum molestiae cumque voluptatum inventore tempore.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 16.9,
      },
      {
        name: "Platy",
        scientificName: "Xiphophorus maculatus",
        image: "https://example.com/fish/platy.jpg",
        minTankSize: 15,
        temperament: "Territorial",
        diet: "Onívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Eius dignissimos reprehenderit iusto dolorem nemo deleniti corrupti dolor minima quaerat veritatis et nisi laboriosam alias.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 14.9,
      },
      {
        name: "Swordtail",
        scientificName: "Xiphophorus hellerii",
        image: "https://example.com/fish/swordtail.jpg",
        minTankSize: 10,
        temperament: "Calmo",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Aut dolorum in mollitia deserunt distinctio illo cumque sit ad pariatur voluptatem quia blanditiis voluptate temporibus excepturi quam maiores corporis nobis saepe.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 24.9,
      },
      {
        name: "Zebra Danio",
        scientificName: "Danio rerio",
        image: "https://example.com/fish/zebra-danio.jpg",
        minTankSize: 15,
        temperament: "Agressivo com machos",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Commodi cum quibusdam necessitatibus corrupti delectus dolorum assumenda delectus provident minima odio deleniti odit suscipit.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 12.9,
      },
      {
        name: "Cherry Barb",
        scientificName: "Puntius titteya",
        image: "https://example.com/fish/cherry-barb.jpg",
        minTankSize: 20,
        temperament: "Calmo",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Autem id dolorem corrupti quia non beatae magnam dolores pariatur omnis suscipit blanditiis unde hic dicta velit corporis.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 13.9,
      },
      {
        name: "Rainbowfish",
        scientificName: "Melanotaenia boesemani",
        image: "https://example.com/fish/rainbowfish.jpg",
        minTankSize: 15,
        temperament: "Pacífico",
        diet: "Herbívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Necessitatibus deserunt sint reprehenderit maxime quod laborum quasi placeat alias quo quaerat ducimus nostrum vel.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 34.9,
      },
      {
        name: "Goldfish",
        scientificName: "Carassius auratus",
        image: "https://example.com/fish/goldfish.jpg",
        minTankSize: 10,
        temperament: "Calmo",
        diet: "Herbívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Impedit libero excepturi magni numquam veritatis cupiditate debitis fugit expedita ratione eveniet quas delectus dolorum veritatis.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 19.9,
      },
      {
        name: "Harlequin Rasbora",
        scientificName: "Trigonostigma heteromorpha",
        image: "https://example.com/fish/harlequin-rasbora.jpg",
        minTankSize: 15,
        temperament: "Agressivo com machos",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Incidunt labore vero earum fugit laborum eum voluptate deserunt tempora rem quos iste.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 16.9,
      },
      {
        name: "Angelfish",
        scientificName: "Pterophyllum scalare",
        image: "https://example.com/fish/angelfish.jpg",
        minTankSize: 20,
        temperament: "Agressivo com machos",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Sapiente modi tempora beatae ullam aliquid vel adipisci consequuntur iste dolorum tempora optio quos distinctio voluptatum voluptatem commodi atque impedit exercitationem unde officiis.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 39.9,
      },
      {
        name: "Zebra Danio",
        scientificName: "Danio rerio",
        image: "https://example.com/fish/zebra-danio.jpg",
        minTankSize: 5,
        temperament: "Pacífico",
        diet: "Onívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Et commodi delectus placeat suscipit mollitia quasi delectus unde deleniti debitis maxime distinctio porro nostrum consectetur dicta asperiores eos fugiat distinctio.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 12.9,
      },
      {
        name: "Harlequin Rasbora",
        scientificName: "Trigonostigma heteromorpha",
        image: "https://example.com/fish/harlequin-rasbora.jpg",
        minTankSize: 5,
        temperament: "Calmo",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Fugiat veniam fugiat atque soluta tempore dolores minima sunt occaecati dignissimos omnis quas inventore animi quis.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 16.9,
      },
      {
        name: "Angelfish",
        scientificName: "Pterophyllum scalare",
        image: "https://example.com/fish/angelfish.jpg",
        minTankSize: 10,
        temperament: "Calmo",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Iusto ipsum placeat labore maxime fugit numquam nulla voluptatum facilis ipsa eveniet modi dolorum eligendi eum.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 39.9,
      },
      {
        name: "Goldfish",
        scientificName: "Carassius auratus",
        image: "https://example.com/fish/goldfish.jpg",
        minTankSize: 5,
        temperament: "Calmo",
        diet: "Onívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Dolorum ea dolore consequatur odit voluptatibus quis impedit dicta odio alias impedit quas eaque eveniet dolore minima porro exercitationem quo totam molestiae harum.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 19.9,
      },
      {
        name: "Discus",
        scientificName: "Symphysodon aequifasciatus",
        image: "https://example.com/fish/discus.jpg",
        minTankSize: 20,
        temperament: "Calmo",
        diet: "Carnívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Illum necessitatibus rerum velit inventore eligendi incidunt delectus veritatis voluptatum voluptatem pariatur molestias voluptate.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 59.9,
      },
      {
        name: "Swordtail",
        scientificName: "Xiphophorus hellerii",
        image: "https://example.com/fish/swordtail.jpg",
        minTankSize: 15,
        temperament: "Calmo",
        diet: "Carnívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Molestiae natus ex quae eveniet eos maxime neque amet a alias iste dicta vel nam occaecati aspernatur placeat perspiciatis totam aut maxime doloribus ipsum in.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 24.9,
      },
      {
        name: "Rainbowfish",
        scientificName: "Melanotaenia boesemani",
        image: "https://example.com/fish/rainbowfish.jpg",
        minTankSize: 15,
        temperament: "Pacífico",
        diet: "Onívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Velit eveniet rem accusamus id pariatur veritatis neque id laboriosam nam aperiam mollitia fugit consectetur praesentium ullam iusto.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 34.9,
      },
      {
        name: "Zebra Danio",
        scientificName: "Danio rerio",
        image: "https://example.com/fish/zebra-danio.jpg",
        minTankSize: 20,
        temperament: "Agressivo com machos",
        diet: "Herbívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Possimus sed saepe deleniti officiis error quos excepturi aperiam nostrum labore ratione impedit nobis recusandae ducimus voluptates assumenda officia voluptatibus minima repellat itaque accusamus repudiandae voluptates.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 12.9,
      },
      {
        name: "Swordtail",
        scientificName: "Xiphophorus hellerii",
        image: "https://example.com/fish/swordtail.jpg",
        minTankSize: 10,
        temperament: "Agressivo com machos",
        diet: "Onívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Quidem eaque reiciendis quaerat nostrum sint corporis inventore illum suscipit odio illum officiis blanditiis corporis exercitationem sit explicabo.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 24.9,
      },
      {
        name: "Cherry Barb",
        scientificName: "Puntius titteya",
        image: "https://example.com/fish/cherry-barb.jpg",
        minTankSize: 10,
        temperament: "Calmo",
        diet: "Carnívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Dolorum ipsam nihil non laboriosam fugiat et voluptas molestias quae nam commodi nesciunt quasi distinctio veniam minima ad voluptas.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 13.9,
      },
      {
        name: "Goldfish",
        scientificName: "Carassius auratus",
        image: "https://example.com/fish/goldfish.jpg",
        minTankSize: 20,
        temperament: "Agressivo com machos",
        diet: "Carnívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Distinctio quae optio facere repellat dolore modi dolore vitae quibusdam at dolorum ut voluptatum porro.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 19.9,
      },
      {
        name: "Molly",
        scientificName: "Poecilia sphenops",
        image: "https://example.com/fish/molly.jpg",
        minTankSize: 20,
        temperament: "Calmo",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Dolorum magni fugit molestias omnis eius dicta blanditiis eius dolorum laboriosam accusamus rem quisquam.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 29.9,
      },
      {
        name: "Molly",
        scientificName: "Poecilia sphenops",
        image: "https://example.com/fish/molly.jpg",
        minTankSize: 10,
        temperament: "Calmo",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Vitae ut consequuntur veniam quidem nobis iusto temporibus eum facere necessitatibus corrupti ea accusamus itaque nesciunt molestias reprehenderit occaecati perspiciatis voluptatum cumque beatae iusto distinctio.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 29.9,
      },
      {
        name: "Angelfish",
        scientificName: "Pterophyllum scalare",
        image: "https://example.com/fish/angelfish.jpg",
        minTankSize: 5,
        temperament: "Agressivo com machos",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Omnis nostrum libero accusamus incidunt totam consectetur ipsa eum et repellat esse autem earum quis nihil exercitationem.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 39.9,
      },
      {
        name: "Harlequin Rasbora",
        scientificName: "Trigonostigma heteromorpha",
        image: "https://example.com/fish/harlequin-rasbora.jpg",
        minTankSize: 5,
        temperament: "Agressivo com machos",
        diet: "Herbívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Asperiores fuga illo excepturi at impedit recusandae explicabo deleniti minus dolores similique cupiditate.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 16.9,
      },
      {
        name: "Discus",
        scientificName: "Symphysodon aequifasciatus",
        image: "https://example.com/fish/discus.jpg",
        minTankSize: 20,
        temperament: "Territorial",
        diet: "Onívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Reiciendis officiis modi dolor ratione molestias iusto ipsum unde at reiciendis est perspiciatis magnam sapiente alias ducimus occaecati nihil dolore rem eius sint pariatur hic quos modi.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 59.9,
      },
      {
        name: "Discus",
        scientificName: "Symphysodon aequifasciatus",
        image: "https://example.com/fish/discus.jpg",
        minTankSize: 15,
        temperament: "Agressivo com machos",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Maxime laboriosam laudantium fugiat atque iste deserunt placeat quidem exercitationem modi odio doloremque a quas sunt placeat doloremque dicta et odio amet itaque.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 59.9,
      },
      {
        name: "Discus",
        scientificName: "Symphysodon aequifasciatus",
        image: "https://example.com/fish/discus.jpg",
        minTankSize: 10,
        temperament: "Territorial",
        diet: "Herbívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Recusandae aliquid possimus quis dolor facilis officiis non distinctio magni aliquid vitae omnis illo recusandae provident corrupti temporibus velit earum debitis.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 59.9,
      },
      {
        name: "Zebra Danio",
        scientificName: "Danio rerio",
        image: "https://example.com/fish/zebra-danio.jpg",
        minTankSize: 10,
        temperament: "Territorial",
        diet: "Onívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Omnis explicabo perspiciatis ex dolorum voluptates veritatis explicabo eaque minima saepe eaque nulla atque unde at enim nulla quae officiis delectus ex molestiae deleniti.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 12.9,
      },
      {
        name: "Harlequin Rasbora",
        scientificName: "Trigonostigma heteromorpha",
        image: "https://example.com/fish/harlequin-rasbora.jpg",
        minTankSize: 20,
        temperament: "Agressivo com machos",
        diet: "Onívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Aliquam velit fuga distinctio occaecati quaerat ducimus aperiam delectus ex eaque voluptatibus pariatur similique nemo quos eum modi mollitia officia harum enim dolores.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 16.9,
      },
      {
        name: "Rainbowfish",
        scientificName: "Melanotaenia boesemani",
        image: "https://example.com/fish/rainbowfish.jpg",
        minTankSize: 15,
        temperament: "Calmo",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.5-7.5",
          temp: "24-28°C",
          gh: "5-12",
        },
        description:
          "Inventore totam sit neque facere fugiat occaecati aperiam deserunt qui unde amet eligendi.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 34.9,
      },
      {
        name: "Angelfish",
        scientificName: "Pterophyllum scalare",
        image: "https://example.com/fish/angelfish.jpg",
        minTankSize: 5,
        temperament: "Pacífico",
        diet: "Herbívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Consequatur magni corrupti a quia dignissimos ullam quos autem culpa repudiandae quidem repudiandae quod doloribus repellat voluptatibus.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 39.9,
      },
      {
        name: "Platy",
        scientificName: "Xiphophorus maculatus",
        image: "https://example.com/fish/platy.jpg",
        minTankSize: 20,
        temperament: "Territorial",
        diet: "Carnívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Suscipit fuga est reprehenderit totam quia dignissimos velit ipsam explicabo animi sed totam laudantium velit dolores eum velit ex nisi mollitia culpa recusandae earum dolor.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 14.9,
      },
      {
        name: "Rainbowfish",
        scientificName: "Melanotaenia boesemani",
        image: "https://example.com/fish/rainbowfish.jpg",
        minTankSize: 5,
        temperament: "Territorial",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Alias iste voluptate eaque magnam perspiciatis magnam corrupti tempora facere accusamus nihil soluta nihil laborum doloremque excepturi.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 34.9,
      },
      {
        name: "Goldfish",
        scientificName: "Carassius auratus",
        image: "https://example.com/fish/goldfish.jpg",
        minTankSize: 5,
        temperament: "Pacífico",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Reprehenderit cumque dolorum quia vero neque error qui id totam odio molestiae debitis nemo non aspernatur maiores esse deleniti expedita corrupti incidunt sequi quas.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 19.9,
      },
      {
        name: "Molly",
        scientificName: "Poecilia sphenops",
        image: "https://example.com/fish/molly.jpg",
        minTankSize: 15,
        temperament: "Pacífico",
        diet: "Onívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Omnis magni aspernatur labore pariatur dolores deleniti dolore asperiores laborum optio eius mollitia quo ipsum omnis mollitia molestiae ea omnis molestias doloremque.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 29.9,
      },
      {
        name: "Swordtail",
        scientificName: "Xiphophorus hellerii",
        image: "https://example.com/fish/swordtail.jpg",
        minTankSize: 20,
        temperament: "Pacífico",
        diet: "Herbívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Soluta ipsam perspiciatis voluptatibus accusamus harum iure illo ullam in eum blanditiis hic.",
        compatibleTankmates: ["Nenhum", "Corydoras (com cautela)", "Tetra"],
        price: 24.9,
      },
      {
        name: "Discus",
        scientificName: "Symphysodon aequifasciatus",
        image: "https://example.com/fish/discus.jpg",
        minTankSize: 20,
        temperament: "Territorial",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Et architecto ad praesentium soluta maiores recusandae amet rerum fugit consequuntur fugit modi fugiat ut tempore placeat dignissimos aspernatur repellendus dicta quos aliquid odit ipsa vitae atque.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 59.9,
      },
      {
        name: "Swordtail",
        scientificName: "Xiphophorus hellerii",
        image: "https://example.com/fish/swordtail.jpg",
        minTankSize: 20,
        temperament: "Territorial",
        diet: "Herbívoro",
        waterParameters: {
          ph: "6.0-7.0",
          temp: "20-26°C",
          gh: "1-5",
        },
        description:
          "Dicta incidunt dolorem dignissimos dolores quos animi necessitatibus nihil sed a sapiente dignissimos omnis reiciendis.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 24.9,
      },
      {
        name: "Goldfish",
        scientificName: "Carassius auratus",
        image: "https://example.com/fish/goldfish.jpg",
        minTankSize: 20,
        temperament: "Agressivo com machos",
        diet: "Carnívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Officia rem eveniet tenetur dolores autem accusantium voluptatem beatae voluptatem sint sequi laudantium praesentium nobis modi sapiente eius veritatis.",
        compatibleTankmates: ["Guppy", "Neon Tetra", "Corydoras"],
        price: 19.9,
      },
      {
        name: "Discus",
        scientificName: "Symphysodon aequifasciatus",
        image: "https://example.com/fish/discus.jpg",
        minTankSize: 20,
        temperament: "Calmo",
        diet: "Onívoro",
        waterParameters: {
          ph: "7.0-8.0",
          temp: "22-30°C",
          gh: "4-10",
        },
        description:
          "Culpa illum sequi unde aliquam in temporibus quis vero iusto dolores quis quidem nostrum sequi labore dolorem molestiae recusandae amet dolor.",
        compatibleTankmates: ["Platy", "Molly", "Zebra Danio"],
        price: 59.9,
      },
    ],
  });

  await prisma.$disconnect();
}

seed()
  .then(() => {
    console.log("Database seeded");
    prisma.$disconnect;
  })
  .catch((e) => {
    console.error(e);
  });
